SOLR_URL_PATTERN = 'http://%s:%s/solr/'
SOLR_URL = SOLR_URL_PATTERN % (SOLR_HOST, SOLR_PORT)

SOLR_INDEXER_BASE = 'http://%s:%s/solrindexer/' % (SOLR_HOST, SOLR_PORT)
SOLR_INDEXER_URL = SOLR_INDEXER_BASE + 'index'

SOLR_MAIN_PATTERN = 'epub/'
SOLR_DS_PATTERN = 'epub_ds/'
SOLR_AC_PATTERN = 'epub_ac/'
SOLR_MAIN_URL = SOLR_URL + SOLR_MAIN_PATTERN
SOLR_DS_URL = SOLR_URL + SOLR_DS_PATTERN
SOLR_AC_URL = SOLR_URL + SOLR_AC_PATTERN
